export const SwapPoolManagerABI = [
  "function seerToken() view returns (address)",
  "function usdtToken() view returns (address)",
  "function dexRouter() view returns (address)",
  "function foundationWallet() view returns (address)",
  "function nodeRewardPool() view returns (address)",
  "function buyTaxBP() view returns (uint256)",
  "function sellTaxBP() view returns (uint256)",
  "function burnShareBP() view returns (uint256)",
  "function nodeShareBP() view returns (uint256)",
  "function totalTaxCollected() view returns (uint256)",
  "function totalBurned() view returns (uint256)",
  "function totalNodeRewards() view returns (uint256)",
  "function totalFoundationFees() view returns (uint256)",
  "function totalSwapCount() view returns (uint256)",
  "function swapSEERForUSDT(uint256 amountIn, uint256 amountOutMin, address to) external returns (uint256 usdtReceived)",
  "function swapUSDTForSEER(uint256 amountIn, uint256 amountOutMin, address to) external returns (uint256 seerReceived)",
  "function quoteSEERForUSDT(uint256 amountIn) view returns (uint256 amountOut, uint256 taxAmount, uint256 afterTaxInput)",
  "function quoteUSDTForSEER(uint256 amountIn) view returns (uint256 amountOut, uint256 taxAmount, uint256 rawSeerOut)",
  "function setTaxRates(uint256 buyTaxBP, uint256 sellTaxBP) external",
  "function setTaxDistribution(uint256 burnShareBP, uint256 nodeShareBP) external",
  "function setDexRouter(address router) external",
  "function setFoundationWallet(address wallet) external",
  "function setNodeRewardPool(address pool) external",
] as const;
